-- AlterTable
ALTER TABLE `todo` ADD COLUMN `dateCompleted` DATETIME(3) NULL,
    ADD COLUMN `dateCreated` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `content` VARCHAR(191) NULL DEFAULT '',
    MODIFY `isCompleted` BOOLEAN NULL DEFAULT false,
    MODIFY `title` VARCHAR(191) NULL DEFAULT '';
